#!/bin/bash
#
#    Copyright 2016 Daniel Alder, https://github.com/daald
#
#    This file is part of dpkg-licenses.
#
#    dpkg-licenses was written by Daniel Alder, https://github.com/daald
#
#    dpkg-licenses is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    dpkg-licenses is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with dpkg-licenses.  If not, see <http://www.gnu.org/licenses/>.

set -e

case "$1" in
  --help|-h)
    cat >&2 <<.e
Lists all installed packages (dpkg -l similar format) and prints their licenses

Usage: $0
.e
    exit 1
esac
pkg=$1

SCRIPTLIB=$(dirname $(readlink -f "$0"))/lib/
test -d "$SCRIPTLIB"

format='%-30s %-30s %-6s %-60s %s\n'
ver=$(uname -m)
if [[ $pkg != "" ]]; then
    if [[ $ver == "x86_64" ]]; then
        echo "# $pkg x86桌面版依赖包许可证列表"
    elif [[ $ver == "mips64" ]]; then
        echo "# $pkg 龙芯桌面版依赖包许可证列表"
    elif [[ $ver == "sw_64" ]]; then
        echo "# $pkg 申威服务器版依赖包许可证列表"
    fi
    echo
else
    if [[ $ver == "x86_64" ]]; then
        echo "# x86桌面版软件包许可证列表"
    elif [[ $ver == "mips64" ]]; then
        echo "# 龙芯桌面版软件包许可证列表"
    elif [[ $ver == "sw_64" ]]; then
        echo "# 申威服务器版软件包许可证列表"
    fi
    echo

fi


printf "$format" "|Name" "|Version" "|Arch" "|Description" "|Licenses|"
echo "|------------------------------|------------------------------|------|------------------------------------------------------------|--------|"

if [[ $pkg != "" ]]; then
    apt-cache depends $pkg | grep -e '^  Depends:' | while read a p; do
        dpkg -l $p | grep '^.[iufhwt]' | while read pState package pVer pArch pDesc; do
            license=
            for method in "$SCRIPTLIB"/reader*; do
            [ -f "$method" ] || continue
            license=$("$method" "$package")
            #echo $License
            [ $? -eq 0 ] || exit 1
            [ -n "$license" ] || continue
            # remove line breaks and spaces
            license=$(echo "$license" | tr '\n' ' ' | sed -r -e 's/ +/ /g' -e 's/^ +//' -e 's/ +$//')
            [ -z "$license" ] || break
            done
            [ -n "$license" ] || license='unknown'
            printf "$format" "|${package:0:30}" "|${pVer:0:30}" "|${pArch:0:6}" "|${pDesc:0:60}" "|$license|"
        done
    done
    exit 0
else
    COLUMNS=2000 dpkg -l | grep '^.[iufhwt]' | while read pState package pVer pArch pDesc; do
    license=
    for method in "$SCRIPTLIB"/reader*; do
    [ -f "$method" ] || continue
    license=$("$method" "$package")
    [ $? -eq 0 ] || exit 1
    [ -n "$license" ] || continue
    # remove line breaks and spaces
    license=$(echo "$license" | tr '\n' ' ' | sed -r -e 's/ +/ /g' -e 's/^ +//' -e 's/ +$//')
    [ -z "$license" ] || break
    done
    [ -n "$license" ] || license='unknown'

    printf "$format" "|${package:0:30}" "|${pVer:0:30}" "|${pArch:0:6}" "|${pDesc:0:60}" "|$license|"
    done
fi

